import taxonomy from "@/content/seo/taxonomy.json";

/**
 * Library category tree — roots, their subcategories, and real prompt counts.
 *
 * SOURCE: src/content/seo/taxonomy.json, regenerated by `pnpm sync:taxonomy`
 * (see scripts/sync-taxonomy.mjs for how the tree is derived — the backend's
 * /api/library/categories is flat and carries no parent field).
 *
 * WHAT CHANGED AND WHY: this module used to read a mirrored `categories.json`
 * from gop-seo — 199 rows that had drifted badly from the live backend. It
 * listed slugs the API no longer serves while missing live ones (which is why
 * /prompt-library/category/financial-modeling answered 404), and it hardcoded
 * ai-agents / audio / video as prompt-free when all three carry prompts.
 *
 * INVARIANT: every term here has ≥1 prompt. Terms with none are omitted at
 * generation time, so nothing in this module can link to an empty page.
 * `count` is the term's own total, so callers can apply a substance floor
 * without a round-trip.
 *
 * ROOT vs SUBCATEGORY MATTERS AT QUERY TIME. The two backend filters are
 * disjoint: `categorySlug` matches roots only and returns 0 for a subcategory,
 * `subCategorySlug` matches children only. Use `filterFor()` to pick — passing
 * the wrong one is why every subcategory page rendered an empty grid.
 */

export type CategoryKind = "root" | "sub";

export type Category = {
  slug: string;
  name: string;
  /** Prompts filed under this exact term. */
  count: number;
  /** Parent slug for a subcategory; null for a root. */
  parent: string | null;
  kind: CategoryKind;
};

type Snapshot = {
  totalPrompts: number | null;
  roots: { slug: string; name: string; count: number }[];
  subcategories: { slug: string; name: string; parent: string; count: number }[];
  tools: { slug: string; name: string; count: number }[];
  audiences: { slug: string; name: string; count: number }[];
  outputTypes: { slug: string; name: string; count: number }[];
};

const SNAP = taxonomy as Snapshot;

const ROOTS: Category[] = SNAP.roots.map((c) => ({ ...c, parent: null, kind: "root" as const }));
const SUBS: Category[] = SNAP.subcategories.map((c) => ({ ...c, kind: "sub" as const }));
const ALL: Category[] = [...ROOTS, ...SUBS];
const BY_SLUG = new Map(ALL.map((c) => [c.slug, c]));

/**
 * Minimum prompts before a term earns its own indexable page.
 *
 * 24 is the grid's page size — "enough to fill the first screen of results".
 * Below it a page is thin by any reasonable measure, and a thin page competing
 * with its own parent category is worse than no page at all. Already the
 * threshold used for the homepage browse chips, kept identical here so a chip
 * and a minted URL never disagree.
 */
export const MIN_PROMPTS_FOR_PAGE = 24;

/** Total published prompts, as of the last taxonomy sync. */
export const TOTAL_PROMPTS = SNAP.totalPrompts;

/* ── lookups ─────────────────────────────────────────────────────────── */

/** Root categories, every one with prompts. */
export function getRootCategories(): Category[] {
  return ROOTS;
}

/** Any term — root or subcategory — by slug. */
export function getCategoryBySlug(slug: string): Category | null {
  return BY_SLUG.get(slug) ?? null;
}

/** True if the slug resolves to a real category page (never link without this). */
export function categorySlugExists(slug: string): boolean {
  return BY_SLUG.has(slug);
}

/** Children of a root, biggest first. Empty for a subcategory. */
export function getSubcategories(slug: string): Category[] {
  return SUBS.filter((c) => c.parent === slug);
}

/** The parent of a subcategory; null for a root or an unknown slug. */
export function parentOf(slug: string): Category | null {
  const cat = BY_SLUG.get(slug);
  return cat?.parent ? BY_SLUG.get(cat.parent) ?? null : null;
}

export function isSubcategory(slug: string): boolean {
  return BY_SLUG.get(slug)?.kind === "sub";
}

/**
 * The correct prompt-feed filter for a term. Roots filter on `categorySlug`,
 * subcategories on `subCategorySlug` — they are NOT interchangeable.
 */
export function filterFor(cat: Category): { categorySlug?: string; subCategorySlug?: string } {
  return cat.kind === "sub" ? { subCategorySlug: cat.slug } : { categorySlug: cat.slug };
}

/* ── what earns a page ───────────────────────────────────────────────── */

/**
 * Terms substantial enough to prerender and advertise in the sitemap.
 *
 * The floor applies at BOTH depths, deliberately. Being a root is not evidence
 * of substance: `ai-agents` and `video` have 2 prompts each and `audio` has 16,
 * so shipping them as indexable pages would be the same thin-page problem the
 * floor exists to prevent, just one level up. They stay reachable and linked —
 * `getRootCategories()` is unfiltered, so navigation still shows them — and
 * `isThin()` marks them noindex until the backend fills them out.
 *
 * Today: 18 of 21 roots, 88 of 142 subcategories.
 */
export function mintableCategories(): Category[] {
  return ALL.filter((c) => c.count >= MIN_PROMPTS_FOR_PAGE);
}

/**
 * Too small to earn indexing. Such a page still renders and still links out
 * (follow), it just doesn't ask to be ranked — the same treatment tool pages
 * already get via toolHasSubstance.
 */
export function isThin(slug: string): boolean {
  const cat = BY_SLUG.get(slug);
  return !cat || cat.count < MIN_PROMPTS_FOR_PAGE;
}

/* ── sibling axes (same snapshot, same ≥1 prompt guarantee) ──────────── */

export type Term = { slug: string; name: string; count: number };

/** Tools with ≥1 prompt — 23 of the backend's 59 tool records. */
export function getPromptedTools(): Term[] {
  return SNAP.tools;
}

/** Audiences with ≥1 prompt. */
export function getPromptedAudiences(): Term[] {
  return SNAP.audiences;
}

/** Output types with ≥1 prompt (text · image · code · presentation). */
export function getPromptedOutputTypes(): Term[] {
  return SNAP.outputTypes;
}

/** Tools substantial enough for their own page. */
export function mintableTools(): Term[] {
  return SNAP.tools.filter((t) => t.count >= MIN_PROMPTS_FOR_PAGE);
}

export function mintableOutputTypes(): Term[] {
  return SNAP.outputTypes.filter((t) => t.count >= MIN_PROMPTS_FOR_PAGE);
}
