export enum CONFIG_ADMIN {
	ADMIN_JWT_SECRET = 'ADMIN_JWT_SECRET',
	ADMIN_JWT_EXPIRES_IN = 'ADMIN_JWT_EXPIRES_IN',
	ADMIN_ROOT_EMAIL = 'ADMIN_ROOT_EMAIL',
	ADMIN_ROOT_PASSWORD = 'ADMIN_ROOT_PASSWORD',
}
