export enum CONFIG {
	NODE_ENV = 'NODE_ENV',

	APP_TITLE = 'APP_TITLE',
	APP_PORT = 'APP_PORT',

	API_KEY = 'API_KEY',
	FREE_REQUESTS_COUNT = 'FREE_REQUESTS_COUNT',

	JWT_SECRET = 'JWT_SECRET',
	JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
	JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',

	POSTMARK_API_KEY = 'POSTMARK_API_KEY',
	EMAIL_FROM_NAME = 'EMAIL_FROM_NAME',
	EMAIL_FROM_ADDRESS = 'EMAIL_FROM_ADDRESS',
	SUPPORT_EMAIL = 'SUPPORT_EMAIL',

	REDIS_HOST = 'REDIS_HOST',
	REDIS_PORT = 'REDIS_PORT',
	REDIS_USER = 'REDIS_USER',
	REDIS_PASSWORD = 'REDIS_PASSWORD',

	GOTENBERG_URL = 'GOTENBERG_URL',
	GOTENBERG_PORT = 'GOTENBERG_PORT',

	MLFLOW_PORT = 'MLFLOW_PORT',
	MLFLOW_TRACKING_URI = 'MLFLOW_TRACKING_URI',
	MLFLOW_BUCKET_NAME = 'MLFLOW_BUCKET_NAME',
	MLFLOW_SECRET_KEY = 'MLFLOW_SECRET_KEY',

	OPENAI_ASST_HTML = 'OPENAI_ASST_HTML',
	OPENAI_CUSTOM_API_KEY = 'OPENAI_CUSTOM_API_KEY',
	OPENAI_INTERNAL_API_KEY = 'OPENAI_INTERNAL_API_KEY',
	OPENAI_CONTEXT_API_KEY = 'OPENAI_CONTEXT_API_KEY',
	ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY',
	GEMINI_API_KEY = 'GEMINI_API_KEY',
	OPENROUTER_API_KEY = 'OPENROUTER_API_KEY',

	NOTION_API_KEY = 'NOTION_API_KEY',
	NOTION_CUSTOM_HISTORY_ID = 'NOTION_CUSTOM_HISTORY_ID',
	NOTION_CUSTOM_PROMPTS_ID = 'NOTION_CUSTOM_PROMPTS_ID',
	NOTION_INTERNAL_PROMPTS_ID = 'NOTION_INTERNAL_PROMPTS_ID',

	GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
	GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
	GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',

	GOOGLE_PROJECT_ID = 'GOOGLE_PROJECT_ID',
	GOOGLE_CLIENT_EMAIL = 'GOOGLE_CLIENT_EMAIL',
	GOOGLE_PRIVATE_KEY = 'GOOGLE_PRIVATE_KEY',
	GOOGLE_MASTER_FOLDER_ID = 'GOOGLE_MASTER_FOLDER_ID',

	STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
	STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',
	STRIPE_PRICE_ID = 'STRIPE_PRICE_ID',
	STRIPE_SUCCESS_URL = 'STRIPE_SUCCESS_URL',
	STRIPE_CANCEL_URL = 'STRIPE_CANCEL_URL',

	URL_SITE_MAIN = 'URL_SITE_MAIN',
	URL_GENERATE_FORM = 'URL_GENERATE_FORM',
	URL_PROMPT_LIBRARY = 'URL_PROMPT_LIBRARY',
	URL_CONTACTS = 'URL_CONTACTS',

	MINIO_PUBLIC_URL = 'MINIO_PUBLIC_URL',
	MINIO_HOST = 'MINIO_HOST',
	MINIO_PORT = 'MINIO_PORT',
	MINIO_USE_SSL = 'MINIO_USE_SSL',
	MINIO_USER = 'MINIO_USER',
	MINIO_PASS = 'MINIO_PASS',
	MINIO_MEDIA_BUCKET = 'MINIO_MEDIA_BUCKET',

	MAIL_USER = 'MAIL_USER',

	QDRANT_URL = 'QDRANT_URL',
	QDRANT_API_KEY = 'QDRANT_API_KEY',
	QDRANT_CRON_SCHEDULE = 'QDRANT_CRON_SCHEDULE',

	FRONTEND_URL = 'FRONTEND_URL',

	POSTMARK_TEMPLATE_SIGNUP_WELCOME = 'POSTMARK_TEMPLATE_SIGNUP_WELCOME',
	POSTMARK_TEMPLATE_SIGNUP_LEAD_MAGNET = 'POSTMARK_TEMPLATE_SIGNUP_LEAD_MAGNET',
	POSTMARK_TEMPLATE_DELIVERY_NOTIFICATION = 'POSTMARK_TEMPLATE_DELIVERY_NOTIFICATION',
	POSTMARK_TEMPLATE_LEAD_MAGNET = 'POSTMARK_TEMPLATE_LEAD_MAGNET',

	BEEHIIV_API_KEY = 'BEEHIIV_API_KEY',
	BEEHIIV_PUBLICATION_GOP_PRODUCTS = 'BEEHIIV_PUBLICATION_GOP_PRODUCTS',
	BEEHIIV_PUBLICATION_GOP_MAIN = 'BEEHIIV_PUBLICATION_GOP_MAIN',
}
